name: test
on: [push]

jobs:
  build:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: linux
      if: runner.os == 'Linux'
      run: |
        echo linux
        ls
    - name: mac
      if: runner.os == 'macOS'
      run: |
        brew install nasm
        echo mac
        ls
    - name: windows
      if: runner.os == 'Windows'
      run: |
        choco install nasm
        nasm -v
        clang++ t.cpp -o t.exe
        ./t.exe

