name: test
on: [push]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-node@v1
    - run: g++ t.cpp && ./a.out
    - run: clang++ t.cpp && ./a.out

